source 'https://rubygems.org'

gem 'berkshelf'
gem 'boom'
gem 'capistrano'
gem 'chef'
gem 'ffi'
gem 'git_fame'
gem 'gitlab'
gem 'hirb'
gem 'httparty'
gem 'knife-backup'
gem 'knife-config'
gem 'knife-ec2'
gem 'knife-linode'
gem 'knife-server'
gem 'knife-solo'
gem 'knife-solo_data_bag'
gem 'knife-windows'
gem 'librarian'
gem 'lunchy'
gem 'mina'
gem 'multi_json'
gem 'powify'
gem 'pry'
gem 'vagrant'
gem 'vagrant-vbguest'


if RUBY_PLATFORM.downcase.include?("darwin")
  gem 'cocoapods'
  gem 'nomad-cli'
end
